name: Build and deploy MEAN stack app to Azure Web App - mean-diss

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies and build frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm run build --if-present

      # Install dependencies and build backend
      - name: Install backend dependencies
        run: |
          cd ../backend
          npm install
          npm run build --if-present

      # Upload both frontend and backend build artifacts
      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/build  # Adjust if needed

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend  # Adjust if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      # Download frontend and backend artifacts from the build job
      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app

      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4471BF22F3E14D85B75D561C5A27D45E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9894EB83F8004550B039AA98CF6669F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27B48037EAA041A48AFB332C4EC50439 }}

      # Deploy backend to Azure Web App
      - name: 'Deploy Backend to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-backend
        with:
          app-name: 'mean-diss-backend'  # Ensure this is the correct backend app name
          slot-name: 'Production'
          package: './backend'  # Path to the backend artifact

      # Deploy frontend to Azure Web App (if it's served as a static website)
      - name: 'Deploy Frontend to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-frontend
        with:
          app-name: 'mean-diss-frontend'  # Ensure this is the correct frontend app name
          slot-name: 'Production'
          package: './frontend/build'  # Path to the frontend build artifact
