name: Build and deploy MEAN stack app to Azure Web App - mean-diss

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build --if-present  # Build Angular frontend

      - name: Install backend dependencies and build
        run: |
          cd backend
          npm install
          npm run build --if-present  # Build Node.js backend

      # Upload frontend and backend build artifacts
      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/dist

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT requests

    steps:
      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app

      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4471BF22F3E14D85B75D561C5A27D45E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9894EB83F8004550B039AA98CF6669F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27B48037EAA041A48AFB332C4EC50439 }}

      
      - name: 'Deploy Backend to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mean-diss'  # The name of your Azure Web App
          resource-group-name: 'azure-mean'  # Your resource group name
          slot-name: 'Production'
          package: .

      - name: 'Deploy Frontend to Azure Web App (into wwwroot)'
        run: |
          # Copy the Angular build into the wwwroot folder of the app
          az webapp deploy --name mean-diss --resource-group azure-mean --src-path . --target-path /home/site/wwwroot
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          
      
      

      - name: Set MongoDB URI as environment variable
        run: |
          az webapp config appsettings set \
            --name mean-diss \
            --resource-group azure-mean \
            --settings MONGO_URI=${{ secrets.MONGO_URI }}  # Set MongoDB URI for the app
