name: Build and deploy MEAN stack app to Azure Web App - mean-diss

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Build Frontend (Angular)
      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build --prod  # Build Angular frontend for production

      # Build Backend (Node.js)
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Upload frontend and backend build artifacts for deployment
      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/dist  # Path to Angular build output

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend  # Ensure backend directory is uploaded

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write  # Required for JWT requests

    steps:
      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app

      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy Frontend to Azure Web App
      - name: Deploy Frontend to Azure Web App
        run: |
          az webapp deploy \
            --name mean-diss \
            --resource-group azure-mean \
            --src-path frontend/dist \
            --target-path /home/site/wwwroot
        env:
          AZURE_WEBAPP_NAME: mean-diss
          AZURE_RESOURCE_GROUP: azure-mean

      # Deploy Backend to Azure Web App
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mean-diss'  # Azure Web App for backend
          resource-group-name: 'azure-mean'
          slot-name: 'production'
          package: './backend'  # Backend folder containing server.js

      # Set MongoDB URI as environment variable for the backend
      - name: Set MongoDB URI as Environment Variable
        run: |
          az webapp config appsettings set \
            --name mean-diss \
            --resource-group azure-mean \
            --settings MONGO_URI=${{ secrets.MONGO_URI }}
